// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/scenario.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ScenarioType  string                 `protobuf:"bytes,2,opt,name=scenario_type,json=scenarioType,proto3" json:"scenario_type,omitempty"`
	Script        string                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartScenarioRequest) Reset() {
	*x = StartScenarioRequest{}
	mi := &file_proto_scenario_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScenarioRequest) ProtoMessage() {}

func (x *StartScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scenario_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScenarioRequest.ProtoReflect.Descriptor instead.
func (*StartScenarioRequest) Descriptor() ([]byte, []int) {
	return file_proto_scenario_proto_rawDescGZIP(), []int{0}
}

func (x *StartScenarioRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartScenarioRequest) GetScenarioType() string {
	if x != nil {
		return x.ScenarioType
	}
	return ""
}

func (x *StartScenarioRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type StartScenarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartScenarioResponse) Reset() {
	*x = StartScenarioResponse{}
	mi := &file_proto_scenario_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScenarioResponse) ProtoMessage() {}

func (x *StartScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scenario_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScenarioResponse.ProtoReflect.Descriptor instead.
func (*StartScenarioResponse) Descriptor() ([]byte, []int) {
	return file_proto_scenario_proto_rawDescGZIP(), []int{1}
}

func (x *StartScenarioResponse) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *StartScenarioResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StopScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopScenarioRequest) Reset() {
	*x = StopScenarioRequest{}
	mi := &file_proto_scenario_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopScenarioRequest) ProtoMessage() {}

func (x *StopScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scenario_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopScenarioRequest.ProtoReflect.Descriptor instead.
func (*StopScenarioRequest) Descriptor() ([]byte, []int) {
	return file_proto_scenario_proto_rawDescGZIP(), []int{2}
}

func (x *StopScenarioRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

type StopScenarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopScenarioResponse) Reset() {
	*x = StopScenarioResponse{}
	mi := &file_proto_scenario_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopScenarioResponse) ProtoMessage() {}

func (x *StopScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scenario_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopScenarioResponse.ProtoReflect.Descriptor instead.
func (*StopScenarioResponse) Descriptor() ([]byte, []int) {
	return file_proto_scenario_proto_rawDescGZIP(), []int{3}
}

func (x *StopScenarioResponse) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *StopScenarioResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetScenarioStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScenarioStatusRequest) Reset() {
	*x = GetScenarioStatusRequest{}
	mi := &file_proto_scenario_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScenarioStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioStatusRequest) ProtoMessage() {}

func (x *GetScenarioStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scenario_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioStatusRequest.ProtoReflect.Descriptor instead.
func (*GetScenarioStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_scenario_proto_rawDescGZIP(), []int{4}
}

func (x *GetScenarioStatusRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

type GetScenarioStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId      string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ScenarioType    string                 `protobuf:"bytes,3,opt,name=scenario_type,json=scenarioType,proto3" json:"scenario_type,omitempty"`
	ContainerId     string                 `protobuf:"bytes,4,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ContainerStatus string                 `protobuf:"bytes,6,opt,name=container_status,json=containerStatus,proto3" json:"container_status,omitempty"`
	Message         string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetScenarioStatusResponse) Reset() {
	*x = GetScenarioStatusResponse{}
	mi := &file_proto_scenario_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScenarioStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioStatusResponse) ProtoMessage() {}

func (x *GetScenarioStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scenario_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioStatusResponse.ProtoReflect.Descriptor instead.
func (*GetScenarioStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_scenario_proto_rawDescGZIP(), []int{5}
}

func (x *GetScenarioStatusResponse) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *GetScenarioStatusResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetScenarioStatusResponse) GetScenarioType() string {
	if x != nil {
		return x.ScenarioType
	}
	return ""
}

func (x *GetScenarioStatusResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *GetScenarioStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetScenarioStatusResponse) GetContainerStatus() string {
	if x != nil {
		return x.ContainerStatus
	}
	return ""
}

func (x *GetScenarioStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTerminalURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTerminalURLRequest) Reset() {
	*x = GetTerminalURLRequest{}
	mi := &file_proto_scenario_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTerminalURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTerminalURLRequest) ProtoMessage() {}

func (x *GetTerminalURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scenario_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTerminalURLRequest.ProtoReflect.Descriptor instead.
func (*GetTerminalURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_scenario_proto_rawDescGZIP(), []int{6}
}

func (x *GetTerminalURLRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

type GetTerminalURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTerminalURLResponse) Reset() {
	*x = GetTerminalURLResponse{}
	mi := &file_proto_scenario_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTerminalURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTerminalURLResponse) ProtoMessage() {}

func (x *GetTerminalURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scenario_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTerminalURLResponse.ProtoReflect.Descriptor instead.
func (*GetTerminalURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_scenario_proto_rawDescGZIP(), []int{7}
}

func (x *GetTerminalURLResponse) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *GetTerminalURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetTerminalURLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetDirectoryStructureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoryStructureRequest) Reset() {
	*x = GetDirectoryStructureRequest{}
	mi := &file_proto_scenario_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoryStructureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryStructureRequest) ProtoMessage() {}

func (x *GetDirectoryStructureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scenario_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryStructureRequest.ProtoReflect.Descriptor instead.
func (*GetDirectoryStructureRequest) Descriptor() ([]byte, []int) {
	return file_proto_scenario_proto_rawDescGZIP(), []int{8}
}

func (x *GetDirectoryStructureRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

type FileNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	IsRoot        bool                   `protobuf:"varint,3,opt,name=is_root,json=isRoot,proto3" json:"is_root,omitempty"`
	Children      []string               `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	IsOpen        bool                   `protobuf:"varint,6,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	IsSaved       bool                   `protobuf:"varint,7,opt,name=is_saved,json=isSaved,proto3" json:"is_saved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileNode) Reset() {
	*x = FileNode{}
	mi := &file_proto_scenario_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileNode) ProtoMessage() {}

func (x *FileNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scenario_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileNode.ProtoReflect.Descriptor instead.
func (*FileNode) Descriptor() ([]byte, []int) {
	return file_proto_scenario_proto_rawDescGZIP(), []int{9}
}

func (x *FileNode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FileNode) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

func (x *FileNode) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *FileNode) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FileNode) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *FileNode) GetIsSaved() bool {
	if x != nil {
		return x.IsSaved
	}
	return false
}

type GetDirectoryStructureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Structure     []*FileNode            `protobuf:"bytes,3,rep,name=structure,proto3" json:"structure,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoryStructureResponse) Reset() {
	*x = GetDirectoryStructureResponse{}
	mi := &file_proto_scenario_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoryStructureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryStructureResponse) ProtoMessage() {}

func (x *GetDirectoryStructureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scenario_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryStructureResponse.ProtoReflect.Descriptor instead.
func (*GetDirectoryStructureResponse) Descriptor() ([]byte, []int) {
	return file_proto_scenario_proto_rawDescGZIP(), []int{10}
}

func (x *GetDirectoryStructureResponse) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *GetDirectoryStructureResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetDirectoryStructureResponse) GetStructure() []*FileNode {
	if x != nil {
		return x.Structure
	}
	return nil
}

func (x *GetDirectoryStructureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_scenario_proto protoreflect.FileDescriptor

const file_proto_scenario_proto_rawDesc = "" +
	"\n" +
	"\x14proto/scenario.proto\x12\bscenario\"l\n" +
	"\x14StartScenarioRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rscenario_type\x18\x02 \x01(\tR\fscenarioType\x12\x16\n" +
	"\x06script\x18\x03 \x01(\tR\x06script\"P\n" +
	"\x15StartScenarioResponse\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"6\n" +
	"\x13StopScenarioRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\"Q\n" +
	"\x14StopScenarioResponse\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\x18GetScenarioStatusRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\"\xfa\x01\n" +
	"\x19GetScenarioStatusResponse\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rscenario_type\x18\x03 \x01(\tR\fscenarioType\x12!\n" +
	"\fcontainer_id\x18\x04 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12)\n" +
	"\x10container_status\x18\x06 \x01(\tR\x0fcontainerStatus\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"8\n" +
	"\x15GetTerminalURLRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\"e\n" +
	"\x16GetTerminalURLResponse\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"?\n" +
	"\x1cGetDirectoryStructureRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\"\xb5\x01\n" +
	"\bFileNode\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\ais_root\x18\x03 \x01(\bR\x06isRoot\x12\x1a\n" +
	"\bchildren\x18\x04 \x03(\tR\bchildren\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x17\n" +
	"\ais_open\x18\x06 \x01(\bR\x06isOpen\x12\x19\n" +
	"\bis_saved\x18\a \x01(\bR\aisSaved\"\xa0\x01\n" +
	"\x1dGetDirectoryStructureResponse\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x120\n" +
	"\tstructure\x18\x03 \x03(\v2\x12.scenario.FileNodeR\tstructure\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\xcf\x03\n" +
	"\x0fScenarioService\x12P\n" +
	"\rStartScenario\x12\x1e.scenario.StartScenarioRequest\x1a\x1f.scenario.StartScenarioResponse\x12M\n" +
	"\fStopScenario\x12\x1d.scenario.StopScenarioRequest\x1a\x1e.scenario.StopScenarioResponse\x12\\\n" +
	"\x11GetScenarioStatus\x12\".scenario.GetScenarioStatusRequest\x1a#.scenario.GetScenarioStatusResponse\x12S\n" +
	"\x0eGetTerminalURL\x12\x1f.scenario.GetTerminalURLRequest\x1a .scenario.GetTerminalURLResponse\x12h\n" +
	"\x15GetDirectoryStructure\x12&.scenario.GetDirectoryStructureRequest\x1a'.scenario.GetDirectoryStructureResponseB\x0eZ\fdevlab/protob\x06proto3"

var (
	file_proto_scenario_proto_rawDescOnce sync.Once
	file_proto_scenario_proto_rawDescData []byte
)

func file_proto_scenario_proto_rawDescGZIP() []byte {
	file_proto_scenario_proto_rawDescOnce.Do(func() {
		file_proto_scenario_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scenario_proto_rawDesc), len(file_proto_scenario_proto_rawDesc)))
	})
	return file_proto_scenario_proto_rawDescData
}

var file_proto_scenario_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_scenario_proto_goTypes = []any{
	(*StartScenarioRequest)(nil),          // 0: scenario.StartScenarioRequest
	(*StartScenarioResponse)(nil),         // 1: scenario.StartScenarioResponse
	(*StopScenarioRequest)(nil),           // 2: scenario.StopScenarioRequest
	(*StopScenarioResponse)(nil),          // 3: scenario.StopScenarioResponse
	(*GetScenarioStatusRequest)(nil),      // 4: scenario.GetScenarioStatusRequest
	(*GetScenarioStatusResponse)(nil),     // 5: scenario.GetScenarioStatusResponse
	(*GetTerminalURLRequest)(nil),         // 6: scenario.GetTerminalURLRequest
	(*GetTerminalURLResponse)(nil),        // 7: scenario.GetTerminalURLResponse
	(*GetDirectoryStructureRequest)(nil),  // 8: scenario.GetDirectoryStructureRequest
	(*FileNode)(nil),                      // 9: scenario.FileNode
	(*GetDirectoryStructureResponse)(nil), // 10: scenario.GetDirectoryStructureResponse
}
var file_proto_scenario_proto_depIdxs = []int32{
	9,  // 0: scenario.GetDirectoryStructureResponse.structure:type_name -> scenario.FileNode
	0,  // 1: scenario.ScenarioService.StartScenario:input_type -> scenario.StartScenarioRequest
	2,  // 2: scenario.ScenarioService.StopScenario:input_type -> scenario.StopScenarioRequest
	4,  // 3: scenario.ScenarioService.GetScenarioStatus:input_type -> scenario.GetScenarioStatusRequest
	6,  // 4: scenario.ScenarioService.GetTerminalURL:input_type -> scenario.GetTerminalURLRequest
	8,  // 5: scenario.ScenarioService.GetDirectoryStructure:input_type -> scenario.GetDirectoryStructureRequest
	1,  // 6: scenario.ScenarioService.StartScenario:output_type -> scenario.StartScenarioResponse
	3,  // 7: scenario.ScenarioService.StopScenario:output_type -> scenario.StopScenarioResponse
	5,  // 8: scenario.ScenarioService.GetScenarioStatus:output_type -> scenario.GetScenarioStatusResponse
	7,  // 9: scenario.ScenarioService.GetTerminalURL:output_type -> scenario.GetTerminalURLResponse
	10, // 10: scenario.ScenarioService.GetDirectoryStructure:output_type -> scenario.GetDirectoryStructureResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_scenario_proto_init() }
func file_proto_scenario_proto_init() {
	if File_proto_scenario_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scenario_proto_rawDesc), len(file_proto_scenario_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scenario_proto_goTypes,
		DependencyIndexes: file_proto_scenario_proto_depIdxs,
		MessageInfos:      file_proto_scenario_proto_msgTypes,
	}.Build()
	File_proto_scenario_proto = out.File
	file_proto_scenario_proto_goTypes = nil
	file_proto_scenario_proto_depIdxs = nil
}
